# Generated by Django 4.0.5 on 2023-02-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_all_items_two'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_items_two',
        ),
    ]
